#!/bin/bash
#wget https://www.dropbox.com/s/0rvxelu4usygefi/ForVirtualMachines.zip

#For basic arch
#sudo pacman -Syy pulseaudio pulseaudio-alsa xf86-input-synaptics xf86-video-fbdev xf86-video-vesa xorg-apps xorg-fonts xorg-server xorg-server-utils xorg-xinit xorg-xkill mesa mesa-vdpau pulseaudio-bluetooth
#sudo pacman -S plasma konsole kate dolphin ark reflector gwenview firefox audacious audacious-plugins screenfetch
#sudo systemctl enable NetworkManager
#sudo systemctl enable bluetooth.service

#Update
#sudo pacman -Syu
#sudo pacman -Syu --noconfirm
sudo apt-get update
sudo apt-get upgrade -y

#Install some stuff
#sudo pacman -S audacious audacious-plugins screenfetch gimp inkscape bleachbit gufw cmatrix htop thunar redshift
sudo apt-get install audacious audacious-plugins gimp inkscape bleachbit gufw cmatrix htop thunar redshift libreoffice brightside

sudo ufw enable

#AUR only stuff
#brightside la-capitaine-icon-theme-git


#Installing the kde display manager
#sudo pacman -Rcns lightdm
#sudo pacman -S sddm-kcm
#sudo systemctl -f enable sddm
#sddm-greeter --test-mode --theme /usr/share/sddm/themes/breeze/


#Sddm stuff
#sudo kate /etc/sddm.conf
#[Theme]
#Current=breeze
#CursorTheme=breeze_cursors
#FacesDir=/usr/share/sddm/faces
#ThemeDir=/usr/share/sddm/themes

#Change grub
echo 
echo "Please change grub. GRUB_CMDLINE_LINUX_DEFAULT=""    "
echo
sudo nano /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg


#To fix the root theming and icons
#XDG_CURRENT_DESKTOP="KDE"
#sudo echo "XDG_CURRENT_DESKTOP=\"KDE\"" >> /etc/environment
sudo nano /etc/environment
kdesu dbus-launch systemsettings5


#Download HackedWhite cursor and hacked serie
cd ~/Downloads
wget https://www.dropbox.com/s/d3a4ne5fcrdjkva/Hacked-White.tgz
tar -xvzf Hacked-White.tgz
mkdir ~/.icons/Hacked-White
mv Hacked-White/ ~/.icons/Hacked-White/

#Doanload test video
cd ~/Downloads
wget http://dl1.vidding.ru/Video/Full006/08321.Pieandbeer-Fiat.Lux.amvnews.ru.mp4

#Video wallpaper
mkdir .local/share/plasma/wallpapers
cd .local/share/plasma/wallpapers
git clone https://github.com/halverneus/org.kde.video.git
